//const words = ["heptagon","octagon","monitor", "tadpoles", "child", "seize", "automatic", "consider", "favourite", "continue", "famous", "hexagon"];
const words = [
    { day: '2024-07-12', words: ["heptagon", "octagon", "monitor", "tadpoles", "child"] },
    { day: '2024-07-13', words: ["seize", "automatic", "consider", "favourite", "continue"] },
    { day: '2024-07-14', words: ["famous", "hexagon", "advocate", "believe", "calculate"] },
    { day: '2024-07-15', words: ["integer", "fraction", "decimal", "subtract", "multiply"] },
    { day: '2024-07-16', words: ["triangle", "quadrilateral", "symmetry", "parallel", "perpendicular"] },
    { day: '2024-07-17', words: ["algebra", "equation", "variable", "constant", "coefficient"] },
    { day: '2024-07-18', words: ["planet", "galaxy", "orbit", "asteroid", "comet"] },
    { day: '2024-07-19', words: ["ecosystem", "habitat", "biodiversity", "species", "niche"] },
    { day: '2024-07-20', words: ["volcano", "earthquake", "tsunami", "eruption", "seismograph"] },
    { day: '2024-07-21', words: ["photosynthesis", "chlorophyll", "glucose", "stomata", "transpiration"] },
    { day: '2024-07-22', words: ["battery", "circuit", "current", "voltage", "resistance"] },
    { day: '2024-07-23', words: ["force", "motion", "gravity", "friction", "inertia"] },
    { day: '2024-07-24', words: ["molecule", "atom", "element", "compound", "reaction"] },
    { day: '2024-07-25', words: ["the", "book", "lok", "sonic", "iron man"] },
    { day: '2024-07-26', words: ["your","that", "book", "on","at","them", "in", "at"] },
    { day: '2024-07-27', words: ["certain", "circle", "different", "eight", "enough"] },
    { day: '2024-07-28', words: ["complete", "consider", "continue", "difficult", "disappear", "early"] },
    { day: '2024-07-29', words: ["exercise", "experience", "favourite", "forwards", "guide"] },
    { day: '2024-07-30', words: ["decide", "describe", "early", "exercise", "february"] },
    { day: '2024-07-31', words: ["century", "decide", "describe", "early", "eight"] },
    { day: '2024-08-01', words: ["experiment", "fruit", "famous", "extreme", "grammar"] },
    { day: '2024-08-02', words: ["interest", "island", "knowledge", "learn", "length"] },
    { day: '2024-08-03', words: ["material", "medicine", "mention", "natural", "naughty"] },
    { day: '2024-08-04', words: ["experience", "exercise", "february", "forwards", "guide"] },
    { day: '2024-08-05', words: ["interest", "island", "knowledge", "learn", "length"] },
    { day: '2024-08-06', words: ["interest", "island", "knowledge", "learn", "length"] },
    { day: '2024-08-07', words: ["material", "medicine", "mention", "natural", "naughty"] },
    { day: '2024-08-08', words: ["material", "medicine", "mention", "natural", "naughty"] },
    { day: '2024-08-09', words: ["particular", "possession", "possible", "popular", "perhaps"] },
    { day: '2024-08-10', words: ["probably", "pressure", "promise", "position", "peculiar"] }
];

